# Kong Cloud Gateway on EKS - TLS Secret Template
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# This is a template file. The actual secret should be created using:
#
#   kubectl create namespace istio-ingress
#   kubectl create secret tls istio-gateway-tls \
#     --cert=certs/server.crt \
#     --key=certs/server.key \
#     -n istio-ingress
#
# OR use the deployment script which handles this automatically:
#   ./scripts/01-generate-certs.sh
#
# The HTTPS listener on the Istio Gateway is optional.
# Kong Cloud Gateway can connect to the internal NLB on port 80 (HTTP).

---
# Template only - do not apply directly
# apiVersion: v1
# kind: Secret
# metadata:
#   name: istio-gateway-tls
#   namespace: istio-ingress
# type: kubernetes.io/tls
# data:
#   tls.crt: <base64-encoded-certificate>
#   tls.key: <base64-encoded-key>
