# Users API Service (Internal NLB)
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# Exposed via internal NLB so Kong Cloud Gateway can reach this service
# through AWS Transit Gateway / VPC Peering.

apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: api
  labels:
    app: users-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: users-api
